version: "3.8"

services:
  backend:
    platform: linux/amd64
    image: lauraleonilla/express-ci-cd:latest
    ports:
      - "8080:8080"
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower